<?php

/**
 * @author  wpWax
 * @since   1.0
 * @version 1.0
 */

class Sanidump_Location_Sitemap
{
    public function __construct()
    {
        // Generate Sitemaps
        add_action('init', array($this, 'generate_sitemap'));
        // Robot Txt
        add_filter('robots_txt', array($this, 'robots_txt'), 10, 2);
        // AIOSEO Sitemap Indexes
        add_filter('aioseo_sitemap_indexes', array($this, 'aioseo_add_sitemap_index'));
    }

    public function generate_sitemap()
    {
        $locations = [];
        $country_args = array(
            'taxonomy' => 'at_biz_dir-location',
            'hide_empty' => false,
            'meta_query' => array(
                array(
                    'key'       => 'sitemap',
                    'value'     => 1,
                    'compare'   => '='
                )
            ),
            'parent' => 0
        );

        $countries = get_terms($country_args);

        if (!$countries || count($countries) < 1) return;

        foreach ($countries as $country) {

            $locations[] = $country;
            $state_args = array(
                'taxonomy' => 'at_biz_dir-location',
                'hide_empty' => false,
                'parent' => $country->term_id
            );

            $states = get_terms($state_args);
            if ($states && count($states) > 0) {
                foreach ($states as $state) {
                    $locations[] = $state;

                    // Cities
                    $city_args = array(
                        'taxonomy' => 'at_biz_dir-location',
                        'hide_empty' => false,
                        'parent' => $state->term_id
                    );
                    $cities = get_terms($city_args);
                    if ($cities && count($cities) > 0) {
                        foreach ($cities as $city) {
                            $locations[] = $city;
                        }
                        //array_merge($locations, $cities);
                    }
                }
            }
        }

        $xml =  '<?xml version="1.0" encoding="' . get_bloginfo('charset') . '"?>' . "\n";
        $xml .=  '<!-- Generated by Custom Sitemap for All in One SEO Pack -->' . "\n";
        $xml .= '<?xml-stylesheet type="text/xsl" href="' . home_url() . '/default.xsl?sitemap=addl"?>';
        $xml .=  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

        foreach ($locations as $location) {

            $directory_types = get_term_meta($location->term_id, '_directory_type', true);

            if ($directory_types) {
                $campground_id = get_taxonomy_id_by_slug('rv-campground', ATBDP_DIRECTORY_TYPE);
                $dumstation_id = get_taxonomy_id_by_slug('rv-dump-station', ATBDP_DIRECTORY_TYPE);

                if (in_array($campground_id, $directory_types)) {
                    $permalink = $this->generate_location_url($location, 'rv-campground');
                    $campground_url = '<url><loc>' . esc_url($permalink) . '</loc><lastmod></lastmod><changefreq><![CDATA[monthly]]></changefreq>
            <priority><![CDATA[0.3]]></priority></url>';
                    $xml .=  $campground_url . "\n";
                }

                if (in_array($dumstation_id, $directory_types)) {
                    $ds_permalink = $this->generate_location_url($location, 'rv-dump-station');
                    $dump_station_url = '<url><loc>' . esc_url($ds_permalink) . '</loc><lastmod></lastmod><changefreq><![CDATA[monthly]]></changefreq>
            <priority><![CDATA[0.3]]></priority></url>';
                    $xml .=  $dump_station_url . "\n";
                }
            }
        }

        $xml .=  '</urlset>' . "\n";

        $file = fopen(ABSPATH . 'location-sitemap.xml', 'w');
        fwrite($file, $xml);
        fclose($file);
    }

    public function robots_txt($robots_txt, $public)
    {
        $sitemap_url = home_url('location-sitemap.xml');
        $robots_txt .= "Sitemap: $sitemap_url\n";
        return $robots_txt;
    }

    public function aioseo_add_sitemap_index($indexes)
    {
        $indexes[] = [
            'loc'     => home_url('location-sitemap.xml'),
            'lastmod' => aioseo()->helpers->dateTimeToIso8601('2022-09-08 12:02'),
            'count' => 10
        ];
        return $indexes;
    }

    public function generate_location_url($location, $directory)
    {
        $directory_type_slug = $directory ? $directory : 'rv-campground';
        $parents = get_term_parents_list($location->term_id, ATBDP_LOCATION, array('inclusive' => false, 'format' => 'slug', 'link' => false));
        $url = get_page_link_by_slug($directory_type_slug) . $parents . $location->slug;
        return $url;
    }
}

new Sanidump_Location_Sitemap();
